# Generated by Django 4.0.6 on 2022-07-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('صبحانه', 'صبحانه'), ('شام', 'شام'), ('ناهار', 'ناهار'), ('نوشیدنی', 'نوشیدنی')], default='شام', max_length=50, verbose_name='نوع غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='descriptions',
            field=models.CharField(max_length=50, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='foods/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='food',
            name='pubdate',
            field=models.DateField(verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.TimeField(verbose_name='زمان'),
        ),
    ]
